/**
 * `pixelcheck completions <shell>` — generate shell completion scripts.
 *
 * Supported shells: bash, zsh, fish.
 *
 * Usage:
 *   pixelcheck completions bash  > ~/.bash_completion.d/pixelcheck
 *   pixelcheck completions zsh   > ~/.zfunc/_pixelcheck
 *   pixelcheck completions fish  > ~/.config/fish/completions/pixelcheck.fish
 *
 * The completions cover all subcommands, global flags, and common option
 * values — generated dynamically from the Commander program tree so they
 * stay in sync with cli.ts without manual maintenance.
 */

import { Command } from "commander";

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────

export interface CommandInfo {
  name: string;
  description: string;
  options: OptionInfo[];
  subcommands: CommandInfo[];
}

export interface OptionInfo {
  flags: string;
  description: string;
  /** Long flag name without leading dashes, e.g. "out" for "--out <dir>". */
  long: string;
  /** Whether the option takes a value argument. */
  takesValue: boolean;
}

export const SUPPORTED_SHELLS = ["bash", "zsh", "fish"] as const;
export type Shell = (typeof SUPPORTED_SHELLS)[number];

// ─────────────────────────────────────────────────────────────
// Introspection — walk Commander tree
// ─────────────────────────────────────────────────────────────

/**
 * Extract structured info from a Commander Command tree. Works recursively
 * for subcommands (e.g. `persona generate`, `persona list-countries`).
 */
export function extractCommands(program: Command): CommandInfo[] {
  const results: CommandInfo[] = [];

  for (const cmd of program.commands as Command[]) {
    const info: CommandInfo = {
      name: cmd.name(),
      description: cmd.description(),
      options: extractOptions(cmd),
      subcommands: extractCommands(cmd),
    };
    results.push(info);
  }

  return results;
}

function extractOptions(cmd: Command): OptionInfo[] {
  return cmd.options.map((opt) => {
    // Commander option.long is e.g. "--out", option.flags is the full spec.
    const long = (opt.long ?? "").replace(/^--/, "").replace(/^no-/, "");
    const takesValue = opt.required || opt.optional;
    return {
      flags: opt.flags,
      description: opt.description,
      long,
      takesValue: !!takesValue,
    };
  });
}

/**
 * Extract global options from the root program (--version, --help, etc.).
 */
export function extractGlobalOptions(program: Command): OptionInfo[] {
  return extractOptions(program);
}

// ─────────────────────────────────────────────────────────────
// Generators
// ─────────────────────────────────────────────────────────────

export function generateCompletion(
  shell: Shell,
  program: Command,
): string {
  const commands = extractCommands(program);
  const globalOpts = extractGlobalOptions(program);

  switch (shell) {
    case "bash":
      return generateBash(commands, globalOpts);
    case "zsh":
      return generateZsh(commands, globalOpts);
    case "fish":
      return generateFish(commands, globalOpts);
  }
}

// ── Bash ────────────────────────────────────────────────────

function generateBash(
  commands: CommandInfo[],
  globalOpts: OptionInfo[],
): string {
  const allCmdNames = flattenCommandNames(commands);
  const globalFlags = globalOpts
    .map((o) => `--${o.long}`)
    .join(" ");

  const caseBlocks = commands
    .map((cmd) => {
      const opts = cmd.options.map((o) => `--${o.long}`).join(" ");
      const subs = cmd.subcommands.map((s) => s.name).join(" ");
      const words = [opts, subs].filter(Boolean).join(" ");

      let block = `        ${cmd.name})\n            COMPREPLY=( $(compgen -W "${words}" -- "$cur") )\n            return 0\n            ;;`;

      // Nested subcommands
      for (const sub of cmd.subcommands) {
        const subOpts = sub.options.map((o) => `--${o.long}`).join(" ");
        block += `\n        ${sub.name})\n            COMPREPLY=( $(compgen -W "${subOpts}" -- "$cur") )\n            return 0\n            ;;`;
      }

      return block;
    })
    .join("\n");

  return `# pixelcheck bash completion — generated by \`pixelcheck completions bash\`
# Install: pixelcheck completions bash > ~/.bash_completion.d/pixelcheck
#   then:  source ~/.bash_completion.d/pixelcheck

_pixelcheck() {
    local cur prev commands
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    commands="${allCmdNames.join(" ")}"

    # Global flags
    if [[ "\${COMP_CWORD}" -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "\${commands} ${globalFlags}" -- "$cur") )
        return 0
    fi

    # Per-command completions
    case "\${COMP_WORDS[1]}" in
${caseBlocks}
        *)
            COMPREPLY=( $(compgen -W "\${commands}" -- "$cur") )
            return 0
            ;;
    esac
}

complete -F _pixelcheck pixelcheck
`;
}

// ── Zsh ─────────────────────────────────────────────────────

function generateZsh(
  commands: CommandInfo[],
  globalOpts: OptionInfo[],
): string {
  const globalFlags = globalOpts
    .map((o) => `'--${o.long}[${escapeZsh(o.description)}]'`)
    .join("\n        ");

  const subcmds = commands
    .map((cmd) => `'${cmd.name}:${escapeZsh(cmd.description)}'`)
    .join("\n            ");

  const cmdCases = commands
    .map((cmd) => {
      const opts = cmd.options
        .map((o) => `'--${o.long}[${escapeZsh(o.description)}]'`)
        .join("\n                ");

      const subs = cmd.subcommands
        .map((s) => `'${s.name}:${escapeZsh(s.description)}'`)
        .join("\n                    ");

      let subCases = "";
      if (cmd.subcommands.length > 0) {
        const subCaseEntries = cmd.subcommands
          .map((s) => {
            const subOpts = s.options
              .map((o) => `'--${o.long}[${escapeZsh(o.description)}]'`)
              .join("\n                        ");
            return `                (${s.name})\n                    _arguments -s \\\n                        ${subOpts}\n                    ;;`;
          })
          .join("\n");

        subCases = `
            local -a ${cmd.name}_subcommands
            ${cmd.name}_subcommands=(
                    ${subs}
            )
            _describe -t commands '${cmd.name} subcommand' ${cmd.name}_subcommands
            case "$words[3]" in
${subCaseEntries}
            esac`;
      }

      return `        (${cmd.name})\n            _arguments -s \\\n                ${opts}${subCases}\n            ;;`;
    })
    .join("\n");

  return `#compdef pixelcheck
# pixelcheck zsh completion — generated by \`pixelcheck completions zsh\`
# Install: pixelcheck completions zsh > ~/.zfunc/_pixelcheck
#   then:  add \`fpath=(~/.zfunc $fpath)\` to ~/.zshrc and run \`compinit\`

_pixelcheck() {
    local -a commands
    commands=(
            ${subcmds}
    )

    _arguments -s \\
        ${globalFlags} \\
        '1:command:->cmd' \\
        '*::arg:->args'

    case "$state" in
        (cmd)
            _describe -t commands 'pixelcheck command' commands
            ;;
        (args)
            case "$words[1]" in
${cmdCases}
            esac
            ;;
    esac
}

_pixelcheck "$@"
`;
}

function escapeZsh(s: string): string {
  return s.replace(/'/g, "'\\''").replace(/\[/g, "\\[").replace(/\]/g, "\\]");
}

// ── Fish ────────────────────────────────────────────────────

function generateFish(
  commands: CommandInfo[],
  globalOpts: OptionInfo[],
): string {
  const lines: string[] = [
    "# pixelcheck fish completion -- generated by `pixelcheck completions fish`",
    "# Install: pixelcheck completions fish > ~/.config/fish/completions/pixelcheck.fish",
    "",
  ];

  // Disable file completions by default
  lines.push("complete -c pixelcheck -f");
  lines.push("");

  // Global options
  for (const opt of globalOpts) {
    lines.push(
      `complete -c pixelcheck -n '__fish_use_subcommand' -l ${opt.long} -d '${escapeFish(opt.description)}'`,
    );
  }
  lines.push("");

  // Subcommands
  const topNames = commands.map((c) => c.name);
  for (const cmd of commands) {
    lines.push(
      `complete -c pixelcheck -n '__fish_use_subcommand' -a '${cmd.name}' -d '${escapeFish(cmd.description)}'`,
    );
  }
  lines.push("");

  // Per-command options
  for (const cmd of commands) {
    const condition =
      cmd.subcommands.length > 0
        ? `__fish_seen_subcommand_from ${cmd.name}`
        : `__fish_seen_subcommand_from ${cmd.name}; and not __fish_seen_subcommand_from ${topNames.filter((n) => n !== cmd.name).join(" ")}`;

    for (const opt of cmd.options) {
      lines.push(
        `complete -c pixelcheck -n '${condition}' -l ${opt.long} -d '${escapeFish(opt.description)}'`,
      );
    }

    // Nested subcommands
    for (const sub of cmd.subcommands) {
      lines.push(
        `complete -c pixelcheck -n '__fish_seen_subcommand_from ${cmd.name}; and not __fish_seen_subcommand_from ${sub.name}' -a '${sub.name}' -d '${escapeFish(sub.description)}'`,
      );
      for (const opt of sub.options) {
        lines.push(
          `complete -c pixelcheck -n '__fish_seen_subcommand_from ${sub.name}' -l ${opt.long} -d '${escapeFish(opt.description)}'`,
        );
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}

function escapeFish(s: string): string {
  return s.replace(/'/g, "\\'");
}

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

function flattenCommandNames(commands: CommandInfo[]): string[] {
  const names: string[] = [];
  for (const cmd of commands) {
    names.push(cmd.name);
    for (const sub of cmd.subcommands) {
      names.push(sub.name);
    }
  }
  return names;
}
