/**
 * Diff report renderers — turn a `RunDiff` into a PR-friendly artefact.
 *
 * The `diffRuns()` core API in history.ts produces structured data
 * (scoreDelta, dimensionDeltas, newIssues[], resolvedIssues[]). This
 * module renders that data into formats CI / PR-review tooling actually
 * consumes:
 *
 *   - Markdown — primary output for GitHub PR comments via
 *     `marocchino/sticky-pull-request-comment` etc. Inline tables,
 *     ▲/▼ trend arrows, severity tags as bold text. GitHub renders
 *     identically; GitLab and Bitbucket also support GFM tables.
 *   - HTML — standalone file for email / Slack / archival. Light
 *     theme matching reporter-pdf + reporter-trends.
 *   - JSON — pass-through of RunDiff plus a small "rendered_at"
 *     metadata block. For tooling that wants to chart or diff its own
 *     way.
 *
 * Severity → arrow / colour mapping is delta-aware:
 *   - Score / per-dimension up = good (▲ green); down = bad (▼ red).
 *   - Issues / cost / duration up = bad (▲ red); down = good (▼ green).
 *   - Zero delta is rendered as "—" with a muted neutral colour.
 *
 * Output is run-id-stamped at the bottom so a recipient can always
 * trace back to the original audit JSON.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { RunDiff } from "./history.js";
import { DEFAULT_LOCALE, t, type Locale, type TranslationKey } from "./i18n.js";

export type DiffReportFormat = "markdown" | "html" | "json" | "text";

export interface DiffReportOptions {
  /** Cap on items shown in new-issues / resolved-issues lists. Default 10. */
  maxIssues?: number;
  /** Include a "generated by" footer. Default true. */
  includeFooter?: boolean;
  /** Locale for the report skeleton. Default 'en'. */
  locale?: Locale;
}

// ─────────────────────────────────────────────────────────────
// Public render helpers (pure)
// ─────────────────────────────────────────────────────────────

/**
 * Render a RunDiff as Markdown. Shape is GitHub-Flavored-Markdown
 * (GFM) — tables, fenced code, emoji. Intended for direct posting
 * as a PR comment via standard GitHub Actions templates.
 */
export function renderDiffMarkdown(
  diff: RunDiff,
  opts: DiffReportOptions = {},
): string {
  const max = opts.maxIssues ?? 10;
  const includeFooter = opts.includeFooter ?? true;
  const locale = opts.locale ?? DEFAULT_LOCALE;
  const lines: string[] = [];
  const A = diff.runA;
  const B = diff.runB;

  lines.push(`## ${t("diff_title", locale)}`);
  lines.push("");
  lines.push(`\`${A.id}\` ${t("baseline", locale)} → \`${B.id}\` ${t("this_run", locale)}`);
  lines.push("");
  if (A.projectName !== B.projectName) {
    lines.push(
      `> **[WARN]** ${t("diff_cross_project", locale)}: \`${A.projectName}\` vs \`${B.projectName}\``,
    );
    lines.push("");
  }

  // Headline metrics table
  lines.push(
    `| ${t("metric", locale)} | ${t("before", locale)} | ${t("after", locale)} | ${t("delta", locale)} |`,
  );
  lines.push("|---|---:|---:|---:|");
  lines.push(
    `| ${t("overall_score", locale)} | ${A.overallScore.toFixed(1)} | ${B.overallScore.toFixed(1)} | ${arrowMd(diff.scoreDelta, "score")} |`,
  );
  lines.push(
    `| ${t("issues", locale)} | ${A.totalIssues} | ${B.totalIssues} | ${arrowMd(diff.issuesDelta, "issues")} |`,
  );
  const critDelta = B.criticalIssues - A.criticalIssues;
  lines.push(
    `| ${t("critical_issues", locale)} | ${A.criticalIssues} | ${B.criticalIssues} | ${arrowMd(critDelta, "issues")} |`,
  );
  lines.push(
    `| ${t("cost", locale)} | $${A.totalCostUsd.toFixed(3)} | $${B.totalCostUsd.toFixed(3)} | ${arrowMd(diff.costDelta, "cost")} |`,
  );
  lines.push(
    `| ${t("duration", locale)} | ${(A.durationMs / 1000).toFixed(0)}s | ${(B.durationMs / 1000).toFixed(0)}s | ${arrowMd(diff.durationDelta / 1000, "duration", "s")} |`,
  );
  lines.push("");

  // Per-dimension changes
  const dimEntries = Object.entries(diff.dimensionDeltas);
  if (dimEntries.length > 0) {
    lines.push(`### ${t("diff_per_dimension_changes", locale)}`);
    lines.push("");
    lines.push(
      `| ${t("dimension", locale)} | ${t("before", locale)} | ${t("after", locale)} | ${t("delta", locale)} |`,
    );
    lines.push("|---|---:|---:|---:|");
    for (const [dim, d] of dimEntries.sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]))) {
      const before = A.dimensionAverages[dim];
      const after = B.dimensionAverages[dim];
      const beforeStr = typeof before === "number" ? before.toFixed(1) : "—";
      const afterStr = typeof after === "number" ? after.toFixed(1) : "—";
      lines.push(
        `| ${dim} | ${beforeStr} | ${afterStr} | ${arrowMd(d, "score")} |`,
      );
    }
    lines.push("");
  }

  // New issues
  if (diff.newIssues.length > 0) {
    lines.push(`### [NEW] ${t("diff_total_new", locale)} (${diff.newIssues.length})`);
    lines.push("");
    for (const i of diff.newIssues.slice(0, max)) {
      lines.push(`- **[${t(i.severity as TranslationKey, locale)}]** ${i.description}`);
    }
    if (diff.newIssues.length > max) {
      lines.push(`- _…and ${diff.newIssues.length - max} more_`);
    }
    lines.push("");
  }

  // Resolved issues
  if (diff.resolvedIssues.length > 0) {
    lines.push(`### [RESOLVED] ${t("diff_total_resolved", locale)} (${diff.resolvedIssues.length})`);
    lines.push("");
    for (const i of diff.resolvedIssues.slice(0, max)) {
      lines.push(`- **[${t(i.severity as TranslationKey, locale)}]** ${i.description}`);
    }
    if (diff.resolvedIssues.length > max) {
      lines.push(`- _…and ${diff.resolvedIssues.length - max} more_`);
    }
    lines.push("");
  }

  if (
    diff.newIssues.length === 0 &&
    diff.resolvedIssues.length === 0 &&
    Math.abs(diff.scoreDelta) < 0.05
  ) {
    lines.push(`_${t("diff_no_changes", locale)}_`);
    lines.push("");
  }

  if (includeFooter) {
    lines.push("---");
    // Translate "Generated by …" but always append a Markdown link to
    // the repo so a recipient browsing the diff can discover the tool.
    // The link target is locale-independent; only the leading prose
    // varies. For locales that drop the brand name in their translation
    // (e.g. zh-CN), append the link explicitly.
    const prefix = t("generated_by", locale);
    const linked = prefix.includes("PixelCheck")
      ? prefix.replace(
          "PixelCheck",
          "[PixelCheck](https://github.com/xcodethink/pixelcheck)",
        )
      : `${prefix} ([PixelCheck](https://github.com/xcodethink/pixelcheck))`;
    lines.push(
      `_${linked} · ${A.projectName} · ${t("diff_footer_tail", locale)} \`${A.id}\` → \`${B.id}\`_`,
    );
  }

  return lines.join("\n");
}

/**
 * Render a RunDiff as a standalone HTML file. Light theme, no
 * external resources — emailable / archivable.
 */
export function renderDiffHtml(
  diff: RunDiff,
  opts: DiffReportOptions = {},
): string {
  const max = opts.maxIssues ?? 10;
  const locale = opts.locale ?? DEFAULT_LOCALE;
  const A = diff.runA;
  const B = diff.runB;
  const critDelta = B.criticalIssues - A.criticalIssues;

  const dimEntries = Object.entries(diff.dimensionDeltas).sort(
    (a, b) => Math.abs(b[1]) - Math.abs(a[1]),
  );

  const dimRows = dimEntries.map((entry) => {
    const [dim, d] = entry;
    const before = A.dimensionAverages[dim];
    const after = B.dimensionAverages[dim];
    return `<tr><td>${escapeHtml(dim)}</td><td class="num">${typeof before === "number" ? before.toFixed(1) : "—"}</td><td class="num">${typeof after === "number" ? after.toFixed(1) : "—"}</td><td class="num">${arrowHtml(d, "score")}</td></tr>`;
  }).join("");

  const newIssuesHtml =
    diff.newIssues.length === 0
      ? ""
      : `<section>
    <h2><span class="badge badge-new">NEW</span> ${escapeHtml(t("diff_total_new", locale))} (${diff.newIssues.length})</h2>
    <ul class="issues">
      ${diff.newIssues
        .slice(0, max)
        .map(
          (i) =>
            `<li class="issue ${escapeAttr(i.severity)}"><span class="sev">${escapeHtml(t(i.severity as TranslationKey, locale))}</span> ${escapeHtml(i.description)}</li>`,
        )
        .join("\n      ")}
      ${diff.newIssues.length > max ? `<li class="more">…and ${diff.newIssues.length - max} more</li>` : ""}
    </ul>
  </section>`;

  const resolvedIssuesHtml =
    diff.resolvedIssues.length === 0
      ? ""
      : `<section>
    <h2><span class="badge badge-resolved">RESOLVED</span> ${escapeHtml(t("diff_total_resolved", locale))} (${diff.resolvedIssues.length})</h2>
    <ul class="issues">
      ${diff.resolvedIssues
        .slice(0, max)
        .map(
          (i) =>
            `<li class="issue resolved"><span class="sev">${escapeHtml(t(i.severity as TranslationKey, locale))}</span> ${escapeHtml(i.description)}</li>`,
        )
        .join("\n      ")}
      ${diff.resolvedIssues.length > max ? `<li class="more">…and ${diff.resolvedIssues.length - max} more</li>` : ""}
    </ul>
  </section>`;

  const noChangesHtml =
    diff.newIssues.length === 0 &&
    diff.resolvedIssues.length === 0 &&
    Math.abs(diff.scoreDelta) < 0.05
      ? `<section><p class="muted"><em>${escapeHtml(t("diff_no_changes", locale))}</em></p></section>`
      : "";

  const crossProjectWarning =
    A.projectName !== B.projectName
      ? `<p class="warning"><strong>[WARN]</strong> ${escapeHtml(t("diff_cross_project", locale))}: <code>${escapeHtml(A.projectName)}</code> vs <code>${escapeHtml(B.projectName)}</code></p>`
      : "";

  return `<!doctype html>
<html lang="${escapeHtml(locale)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(t("diff_title", locale))} — ${escapeHtml(A.projectName)}</title>
<style>${diffStylesheet()}</style>
</head>
<body>
<div class="container">
  <header>
    <h1>${escapeHtml(t("diff_title", locale))}</h1>
    <p class="meta"><code>${escapeHtml(A.id)}</code> ${escapeHtml(t("baseline", locale))} → <code>${escapeHtml(B.id)}</code> ${escapeHtml(t("this_run", locale))}</p>
    ${crossProjectWarning}
  </header>

  <section>
    <h2>${escapeHtml(t("diff_headline_metrics", locale))}</h2>
    <table class="metrics">
      <thead><tr><th>${escapeHtml(t("metric", locale))}</th><th>${escapeHtml(t("before", locale))}</th><th>${escapeHtml(t("after", locale))}</th><th>${escapeHtml(t("delta", locale))}</th></tr></thead>
      <tbody>
        <tr><td>${escapeHtml(t("overall_score", locale))}</td><td class="num">${A.overallScore.toFixed(1)}</td><td class="num">${B.overallScore.toFixed(1)}</td><td class="num">${arrowHtml(diff.scoreDelta, "score")}</td></tr>
        <tr><td>${escapeHtml(t("issues", locale))}</td><td class="num">${A.totalIssues}</td><td class="num">${B.totalIssues}</td><td class="num">${arrowHtml(diff.issuesDelta, "issues")}</td></tr>
        <tr><td>${escapeHtml(t("critical_issues", locale))}</td><td class="num">${A.criticalIssues}</td><td class="num">${B.criticalIssues}</td><td class="num">${arrowHtml(critDelta, "issues")}</td></tr>
        <tr><td>${escapeHtml(t("cost", locale))}</td><td class="num">$${A.totalCostUsd.toFixed(3)}</td><td class="num">$${B.totalCostUsd.toFixed(3)}</td><td class="num">${arrowHtml(diff.costDelta, "cost")}</td></tr>
        <tr><td>${escapeHtml(t("duration", locale))}</td><td class="num">${(A.durationMs / 1000).toFixed(0)}s</td><td class="num">${(B.durationMs / 1000).toFixed(0)}s</td><td class="num">${arrowHtml(diff.durationDelta / 1000, "duration", "s")}</td></tr>
      </tbody>
    </table>
  </section>

  ${dimEntries.length > 0
    ? `<section>
    <h2>${escapeHtml(t("diff_per_dimension_changes", locale))}</h2>
    <table class="metrics">
      <thead><tr><th>${escapeHtml(t("dimension", locale))}</th><th>${escapeHtml(t("before", locale))}</th><th>${escapeHtml(t("after", locale))}</th><th>${escapeHtml(t("delta", locale))}</th></tr></thead>
      <tbody>${dimRows}</tbody>
    </table>
  </section>`
    : ""}

  ${newIssuesHtml}
  ${resolvedIssuesHtml}
  ${noChangesHtml}

  <footer>
    ${escapeHtml(t("generated_by", locale))} · ${escapeHtml(A.projectName)} · ${escapeHtml(t("diff_footer_tail", locale))} <code>${escapeHtml(A.id)}</code> → <code>${escapeHtml(B.id)}</code>
  </footer>
</div>
</body>
</html>`;
}

/**
 * Render a RunDiff as JSON. Pass-through of the structured data plus a
 * small `rendered_at` block for tools that want to chart / aggregate.
 */
export function renderDiffJson(diff: RunDiff): string {
  return JSON.stringify(
    {
      kind: "audit_diff",
      rendered_at: new Date().toISOString(),
      diff,
    },
    null,
    2,
  );
}

/**
 * Render a RunDiff as the original CLI text format. Identical layout
 * the existing `pixelcheck diff` command produces — exposed here so the
 * --format flag can route through the same renderer set.
 *
 * No ANSI colour: this format is for non-TTY consumers (logs / file
 * redirection). The CLI's interactive path uses chalk directly.
 */
export function renderDiffText(diff: RunDiff): string {
  const lines: string[] = [];
  const A = diff.runA;
  const B = diff.runB;
  const fmt = (v: number, unit = "") =>
    `${v > 0 ? "+" : ""}${v.toFixed(unit === "" && Number.isInteger(v) ? 0 : 1)}${unit}`;

  lines.push(`Diff: ${A.id} -> ${B.id}`);
  lines.push("");
  lines.push(
    `  Overall Score: ${A.overallScore.toFixed(1)} -> ${B.overallScore.toFixed(1)} (${fmt(diff.scoreDelta)})`,
  );
  lines.push(
    `  Issues:        ${A.totalIssues} -> ${B.totalIssues} (${fmt(diff.issuesDelta)})`,
  );
  lines.push(
    `  Cost:          $${A.totalCostUsd.toFixed(3)} -> $${B.totalCostUsd.toFixed(3)} (${fmt(diff.costDelta)})`,
  );
  lines.push(
    `  Duration:      ${(A.durationMs / 1000).toFixed(0)}s -> ${(B.durationMs / 1000).toFixed(0)}s`,
  );

  const dimEntries = Object.entries(diff.dimensionDeltas);
  if (dimEntries.length > 0) {
    lines.push("");
    lines.push("  Dimension deltas:");
    for (const [dim, d] of dimEntries) {
      lines.push(`    ${dim}: ${fmt(d)}`);
    }
  }
  if (diff.newIssues.length > 0) {
    lines.push("");
    lines.push(`  New issues (${diff.newIssues.length}):`);
    for (const i of diff.newIssues.slice(0, 10)) {
      lines.push(`    [${i.severity}] ${i.description.slice(0, 100)}`);
    }
  }
  if (diff.resolvedIssues.length > 0) {
    lines.push("");
    lines.push(`  Resolved issues (${diff.resolvedIssues.length}):`);
    for (const i of diff.resolvedIssues.slice(0, 10)) {
      lines.push(`    [${i.severity}] ${i.description.slice(0, 100)}`);
    }
  }
  return lines.join("\n");
}

/**
 * Write a diff report to disk in the requested format. Returns the
 * absolute output path. Format is inferred from the filename extension
 * unless `format` is explicitly set.
 */
export function writeDiffReport(
  diff: RunDiff,
  outPath: string,
  format?: DiffReportFormat,
  opts: DiffReportOptions = {},
): string {
  const resolved = path.resolve(outPath);
  const fmt = format ?? formatFromExtension(resolved);
  let content: string;
  switch (fmt) {
    case "markdown":
      content = renderDiffMarkdown(diff, opts);
      break;
    case "html":
      content = renderDiffHtml(diff, opts);
      break;
    case "json":
      content = renderDiffJson(diff);
      break;
    case "text":
      content = renderDiffText(diff);
      break;
    default:
      throw new Error(`Unknown diff report format: ${String(fmt)}`);
  }
  fs.mkdirSync(path.dirname(resolved), { recursive: true });
  fs.writeFileSync(resolved, content);
  return resolved;
}

// ─────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────

type DeltaKind = "score" | "issues" | "cost" | "duration";

/**
 * Markdown delta arrow. "score" goes up = good (▲); "issues"/"cost"/
 * "duration" go up = bad (▲ red). Returns plain Markdown text — no
 * HTML, no inline styles, GFM-portable.
 */
function arrowMd(delta: number, kind: DeltaKind, unit = ""): string {
  if (Math.abs(delta) < 1e-6 || (kind === "issues" && delta === 0)) {
    return "—";
  }
  const isImprovement =
    kind === "score" ? delta > 0 : delta < 0;
  const arrow = delta > 0 ? "▲" : "▼";
  const formatted = formatDelta(delta, kind, unit);
  // GFM doesn't honour <span style>; we encode polarity via inline
  // text labels [OK] / [WARN] (CLAUDE.md 铁律 #10 — 通知中禁止 emoji；
  // PR diff comments are notification channel posted into GitHub PRs).
  const polarity = isImprovement ? "[OK]" : "[WARN]";
  return `${arrow} ${formatted} ${polarity}`;
}

function formatDelta(delta: number, kind: DeltaKind, unit: string): string {
  const sign = delta > 0 ? "+" : "";
  if (kind === "issues") {
    return `${sign}${Math.round(delta)}${unit}`;
  }
  if (kind === "cost") {
    return `${delta < 0 ? "-" : "+"}$${Math.abs(delta).toFixed(3)}`;
  }
  // score / duration / generic — 1 decimal
  return `${sign}${delta.toFixed(1)}${unit}`;
}

/**
 * HTML delta arrow with inline colour. Wrapped in a span carrying
 * a `delta-{up|down|flat}` class for stylesheet targeting.
 */
function arrowHtml(delta: number, kind: DeltaKind, unit = ""): string {
  if (Math.abs(delta) < 1e-6 || (kind === "issues" && delta === 0)) {
    return `<span class="delta flat">—</span>`;
  }
  const isImprovement =
    kind === "score" ? delta > 0 : delta < 0;
  const cls = isImprovement ? "up" : "down";
  const arrow = delta > 0 ? "▲" : "▼";
  return `<span class="delta ${cls}">${arrow} ${formatDelta(delta, kind, unit)}</span>`;
}

function formatFromExtension(filePath: string): DiffReportFormat {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".md" || ext === ".markdown") return "markdown";
  if (ext === ".html" || ext === ".htm") return "html";
  if (ext === ".json") return "json";
  return "text";
}

function diffStylesheet(): string {
  return `
    * { box-sizing: border-box; }
    body {
      margin: 0; padding: 24px;
      background: #fafafa; color: #111;
      font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif;
      font-size: 14px; line-height: 1.55;
    }
    .container { max-width: 880px; margin: 0 auto; }
    header h1 { color: #1e3a8a; font-size: 22px; margin: 0 0 4px; }
    header .meta { color: #444; font-size: 13px; margin: 0 0 6px; }
    header code { font-size: 12px; background: #f1f5f9; padding: 1px 6px; border-radius: 3px; }
    .warning { background: #fef3c7; border-left: 3px solid #a16207; padding: 8px 12px; color: #854d0e; margin-top: 8px; border-radius: 0 4px 4px 0; }
    section { margin-top: 24px; background: #fff; border: 1px solid #e5e7eb; border-radius: 6px; padding: 14px 18px; }
    h2 { font-size: 15px; margin: 0 0 10px; color: #111; }
    table.metrics { width: 100%; border-collapse: collapse; }
    table.metrics th, table.metrics td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; font-size: 13px; }
    table.metrics th { color: #555; text-align: left; font-weight: 600; background: #f8fafc; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .delta.up { color: #15803d; font-weight: 600; }
    .delta.down { color: #b91c1c; font-weight: 600; }
    .delta.flat { color: #888; }
    ul.issues { padding-left: 0; list-style: none; margin: 0; }
    .issue { padding: 8px 12px; border-left: 3px solid #ccc; background: #f8fafc; border-radius: 0 4px 4px 0; margin-bottom: 6px; font-size: 13px; }
    .issue.critical, .issue.high { border-left-color: #b91c1c; background: #fef2f2; }
    .issue.medium { border-left-color: #a16207; background: #fffbeb; }
    .issue.low { border-left-color: #6b7280; }
    .issue.resolved { border-left-color: #15803d; background: #f0fdf4; }
    .sev {
      display: inline-block; font-size: 10px; font-weight: 700;
      text-transform: uppercase; padding: 1px 6px; border-radius: 3px;
      background: #e5e7eb; color: #374151; margin-right: 6px; letter-spacing: 0.5px;
    }
    .more { font-style: italic; color: #888; padding: 4px 12px; }
    .muted { color: #888; }
    footer {
      margin-top: 18px; padding-top: 8px; border-top: 1px solid #e5e7eb;
      font-size: 11px; color: #888; text-align: center;
    }
    code { background: #f1f5f9; padding: 1px 4px; border-radius: 2px; font-size: 12px; }
  `;
}

export function escapeHtml(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) => {
    switch (c) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      case "'":
        return "&#39;";
    }
    return c;
  });
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}
